# Generated by Django 4.2.4 on 2023-08-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='chat_id',
        ),
    ]
